[project]
name = "ppgee0018"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.6",
    "notebook>=7.4.5",
    "scipy>=1.16.2",
    "seaborn>=0.13.2",
]
